/**
 * Core domain types for the IP-SAKTI Sahayak pipeline.
 * These types define the full user flow: Intent → Context → Answer.
 *
 * See context.md §1 and §3b for the pipeline definition.
 * Aligned with backend/app/schemas/context.py as of 2026-08-29.
 */

/** The 6 user-facing domain intents shown on the landing page */
export type DomainIntent =
  | 'BUSINESS'
  | 'EXPORT'
  | 'MEDICINAL'
  | 'PATENT'
  | 'RESEARCH'
  | 'OTHER'

/** Answer input type for a context-gathering question (frontend UI types) */
export type AnswerType = 'text' | 'select' | 'multi_select' | 'radio' | 'checkbox'

/**
 * A single context-gathering question generated by the AI (T3.5).
 * Aligned with backend ContextQuestion schema.
 */
export interface ContextQuestion {
  id: string
  question_text: string
  answer_type: AnswerType
  options?: string[]
  required: boolean
  placeholder?: string
  help_text?: string
}

/**
 * The structured context object assembled from user answers.
 */
export interface ContextObject {
  domain_intent: DomainIntent
  answers: Record<string, string | string[]>
  free_description?: string
}

/**
 * Entities extracted from the context (T3.6).
 * Aligned with AI layer EntitySet dataclass.
 */
export interface EntitySet {
  herbs: string[]
  jurisdictions: string[]
  ip_types: string[]
  biological_resources: string[]
  formulation_name: string | null
  destination_country: string | null
  regulatory_regime: string | null
}
