/**
 * Core domain types for the IP-SAKTI Sahayak pipeline.
 * These types define the full user flow: Intent → Context → Answer.
 *
 * See context.md §1 and §3b for the pipeline definition.
 */

/** The 6 user-facing domain intents shown on the landing page */
export type DomainIntent =
  | 'BUSINESS'
  | 'EXPORT'
  | 'MEDICINAL'
  | 'PATENT'
  | 'RESEARCH'
  | 'OTHER'

/** Answer input type for a context-gathering question */
export type AnswerType = 'text' | 'select' | 'multi_select' | 'radio' | 'checkbox'

/**
 * A single context-gathering question generated by the AI (T3.5).
 * // TODO(contract): confirm ContextQuestion schema against ai/status.md once T3.5 is done.
 */
export interface ContextQuestion {
  id: string
  question_text: string
  answer_type: AnswerType
  options?: string[]
  required: boolean
  placeholder?: string
}

/**
 * The structured context object assembled from user answers.
 * // TODO(contract): confirm ContextObject schema against ai/status.md once T3.5 is done.
 */
export interface ContextObject {
  domain_intent: DomainIntent
  answers: Record<string, string | string[]>
  free_description?: string
}

/**
 * Entities extracted from the context (T3.6).
 * // TODO(contract): confirm EntitySet schema against ai/status.md once T3.6 is done.
 */
export interface EntitySet {
  herbs: string[]
  jurisdictions: string[]
  ip_types: string[]
  product_types: string[]
  regulations: string[]
  organizations: string[]
}
