"""LLM Provider abstraction layer.

Provides a unified interface for multiple LLM providers (Gemini, OpenAI, Anthropic).
Never call provider SDKs directly in pipeline code — always use LLMProvider.
"""

from abc import ABC, abstractmethod
from typing import Any, Optional
import json
import os
import urllib.request
import urllib.error


class LLMProvider(ABC):
    """Abstract base class for all LLM providers."""

    def __init__(self, model_name: str, api_key: str):
        self.model_name = model_name
        self.api_key = api_key

    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        """Synchronously generate text response from the LLM.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query / evidence context prompt.
            **kwargs: Provider-specific inference parameters (temperature, max_tokens, etc.)

        Returns:
            The raw text generated by the model.
        """
        pass

    @abstractmethod
    async def generate_async(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        """Asynchronously generate text response from the LLM.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query / evidence context prompt.
            **kwargs: Provider-specific inference parameters (temperature, max_tokens, etc.)

        Returns:
            The raw text generated by the model.
        """
        pass


class GeminiProvider(LLMProvider):
    """Concrete implementation for Google Gemini models.

    Supports the modern `google-genai` SDK, legacy `google-generativeai` SDK,
    and direct REST API fallback.
    """

    def __init__(self, model_name: str = "gemini-2.0-flash", api_key: Optional[str] = None):
        key = api_key or os.getenv("LLM_API_KEY")
        if not key:
            try:
                from src.config import settings
                key = getattr(settings, "llm_api_key", None)
            except Exception:
                pass
        if not key:
            raise ValueError("API key must be provided for GeminiProvider or set via LLM_API_KEY.")
        super().__init__(model_name=model_name, api_key=key)

    def _generate_via_google_genai(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> Optional[str]:
        try:
            from google import genai
            from google.genai import types
            client = genai.Client(api_key=self.api_key)

            config_kwargs: dict[str, Any] = {}
            if system_prompt:
                config_kwargs["system_instruction"] = system_prompt
            if "temperature" in kwargs:
                config_kwargs["temperature"] = kwargs["temperature"]
            if "max_tokens" in kwargs:
                config_kwargs["max_output_tokens"] = kwargs["max_tokens"]
            if "top_p" in kwargs:
                config_kwargs["top_p"] = kwargs["top_p"]

            config = types.GenerateContentConfig(**config_kwargs) if config_kwargs else None
            response = client.models.generate_content(
                model=self.model_name,
                contents=user_prompt,
                config=config,
            )
            return response.text or ""
        except ImportError:
            return None

    def _generate_via_legacy_genai(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> Optional[str]:
        try:
            import google.generativeai as legacy_genai
            legacy_genai.configure(api_key=self.api_key)

            model_kwargs: dict[str, Any] = {}
            if system_prompt:
                model_kwargs["system_instruction"] = system_prompt

            generation_config = {}
            if "temperature" in kwargs:
                generation_config["temperature"] = kwargs["temperature"]
            if "max_tokens" in kwargs:
                generation_config["max_output_tokens"] = kwargs["max_tokens"]
            if "top_p" in kwargs:
                generation_config["top_p"] = kwargs["top_p"]

            model = legacy_genai.GenerativeModel(model_name=self.model_name, **model_kwargs)
            response = model.generate_content(
                user_prompt,
                generation_config=generation_config if generation_config else None
            )
            return response.text or ""
        except ImportError:
            return None

    def _generate_via_rest(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        headers = {"Content-Type": "application/json"}
        contents = [{"role": "user", "parts": [{"text": user_prompt}]}]
        body: dict[str, Any] = {"contents": contents}

        if system_prompt:
            body["systemInstruction"] = {"parts": [{"text": system_prompt}]}

        gen_config: dict[str, Any] = {}
        if "temperature" in kwargs:
            gen_config["temperature"] = kwargs["temperature"]
        if "max_tokens" in kwargs:
            gen_config["maxOutputTokens"] = kwargs["max_tokens"]
        if "top_p" in kwargs:
            gen_config["topP"] = kwargs["top_p"]
        if gen_config:
            body["generationConfig"] = gen_config

        req = urllib.request.Request(url, data=json.dumps(body).encode("utf-8"), headers=headers)
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            candidates = data.get("candidates", [])
            if not candidates:
                return ""
            parts = candidates[0].get("content", {}).get("parts", [])
            return "".join(p.get("text", "") for p in parts)

    def generate(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        # Try modern google-genai SDK first
        res = self._generate_via_google_genai(system_prompt, user_prompt, **kwargs)
        if res is not None:
            return res

        # Try legacy google-generativeai SDK
        res = self._generate_via_legacy_genai(system_prompt, user_prompt, **kwargs)
        if res is not None:
            return res

        # Fallback to direct REST API
        return self._generate_via_rest(system_prompt, user_prompt, **kwargs)

    async def generate_async(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        try:
            from google import genai
            from google.genai import types
            client = genai.Client(api_key=self.api_key)

            config_kwargs: dict[str, Any] = {}
            if system_prompt:
                config_kwargs["system_instruction"] = system_prompt
            if "temperature" in kwargs:
                config_kwargs["temperature"] = kwargs["temperature"]
            if "max_tokens" in kwargs:
                config_kwargs["max_output_tokens"] = kwargs["max_tokens"]

            config = types.GenerateContentConfig(**config_kwargs) if config_kwargs else None
            response = await client.aio.models.generate_content(
                model=self.model_name,
                contents=user_prompt,
                config=config,
            )
            return response.text or ""
        except ImportError:
            pass

        # Fallback to sync execution for async call if async SDK not available
        return self.generate(system_prompt, user_prompt, **kwargs)


class OpenAIProvider(LLMProvider):
    """Concrete implementation for OpenAI models via openai SDK."""

    def __init__(self, model_name: str = "gpt-4o", api_key: Optional[str] = None):
        key = api_key or os.getenv("LLM_API_KEY")
        if not key:
            raise ValueError("API key must be provided for OpenAIProvider or set via LLM_API_KEY.")
        super().__init__(model_name=model_name, api_key=key)

    def _get_client(self):
        try:
            from openai import OpenAI
            return OpenAI(api_key=self.api_key)
        except ImportError as e:
            raise ImportError(
                "openai package is required for OpenAIProvider. "
                "Install with: pip install openai"
            ) from e

    def _get_async_client(self):
        try:
            from openai import AsyncOpenAI
            return AsyncOpenAI(api_key=self.api_key)
        except ImportError as e:
            raise ImportError(
                "openai package is required for OpenAIProvider. "
                "Install with: pip install openai"
            ) from e

    def generate(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        client = self._get_client()
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": user_prompt})

        response = client.chat.completions.create(
            model=self.model_name,
            messages=messages,
            **kwargs
        )
        return response.choices[0].message.content or ""

    async def generate_async(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        client = self._get_async_client()
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": user_prompt})

        response = await client.chat.completions.create(
            model=self.model_name,
            messages=messages,
            **kwargs
        )
        return response.choices[0].message.content or ""


class AnthropicProvider(LLMProvider):
    """Concrete implementation for Anthropic Claude models via anthropic SDK."""

    def __init__(self, model_name: str = "claude-3-5-sonnet-20241022", api_key: Optional[str] = None):
        key = api_key or os.getenv("LLM_API_KEY")
        if not key:
            raise ValueError("API key must be provided for AnthropicProvider or set via LLM_API_KEY.")
        super().__init__(model_name=model_name, api_key=key)

    def _get_client(self):
        try:
            from anthropic import Anthropic
            return Anthropic(api_key=self.api_key)
        except ImportError as e:
            raise ImportError(
                "anthropic package is required for AnthropicProvider. "
                "Install with: pip install anthropic"
            ) from e

    def _get_async_client(self):
        try:
            from anthropic import AsyncAnthropic
            return AsyncAnthropic(api_key=self.api_key)
        except ImportError as e:
            raise ImportError(
                "anthropic package is required for AnthropicProvider. "
                "Install with: pip install anthropic"
            ) from e

    def generate(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        client = self._get_client()
        params: dict[str, Any] = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": user_prompt}],
            "max_tokens": kwargs.pop("max_tokens", 4096),
            **kwargs
        }
        if system_prompt:
            params["system"] = system_prompt

        response = client.messages.create(**params)
        block = response.content[0]
        return getattr(block, "text", "")

    async def generate_async(self, system_prompt: str, user_prompt: str, **kwargs: Any) -> str:
        client = self._get_async_client()
        params: dict[str, Any] = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": user_prompt}],
            "max_tokens": kwargs.pop("max_tokens", 4096),
            **kwargs
        }
        if system_prompt:
            params["system"] = system_prompt

        response = await client.messages.create(**params)
        block = response.content[0]
        return getattr(block, "text", "")


def get_llm_provider(
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> LLMProvider:
    """Factory function to instantiate the configured LLM provider.

    Reads from function arguments if supplied, otherwise falls back to environment
    variables (`LLM_PROVIDER`, `LLM_MODEL`, `LLM_API_KEY`).

    Args:
        provider: Provider name ('gemini', 'openai', 'anthropic').
        model: Model name.
        api_key: Provider API key.

    Returns:
        An instance of LLMProvider.
    """
    try:
        from src.config import settings
    except Exception:
        settings = None

    provider_name = (
        provider
        or os.getenv("LLM_PROVIDER")
        or (getattr(settings, "llm_provider", None) if settings else None)
        or "gemini"
    ).lower()
    model_name = (
        model
        or os.getenv("LLM_MODEL")
        or (getattr(settings, "llm_model", None) if settings else None)
    )
    key = (
        api_key
        or os.getenv("LLM_API_KEY")
        or (getattr(settings, "llm_api_key", None) if settings else None)
    )

    if provider_name == "gemini":
        return GeminiProvider(
            model_name=model_name or "gemini-2.0-flash",
            api_key=key,
        )
    elif provider_name == "openai":
        return OpenAIProvider(
            model_name=model_name or "gpt-4o",
            api_key=key,
        )
    elif provider_name == "anthropic":
        return AnthropicProvider(
            model_name=model_name or "claude-3-5-sonnet-20241022",
            api_key=key,
        )
    else:
        raise ValueError(
            f"Unsupported LLM provider '{provider_name}'. "
            "Supported providers: 'gemini', 'openai', 'anthropic'."
        )
